version: "3.9"
services:
  db :
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - restaurant
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/restaurant
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - restaurant
      
networks:
  restaurant:
    driver: bridge
volumes:
  data:
