# Generated by Django 4.1.2 on 2022-10-31 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='FoodAndDrinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('rating', models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True, verbose_name='Рейтинг')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Граммовка')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.category', verbose_name='Категория')),
            ],
        ),
    ]
