# Generated by Django 4.1.2 on 2022-10-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_foodanddrinks_delete_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodanddrinks',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='foodanddrinks',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='foodanddrinks',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='foodanddrinks',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Граммовка'),
        ),
    ]
