# Generated by Django 4.1.2 on 2022-11-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Ваш отзыв'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Имя'),
        ),
    ]
